# First, add the API
apiVersion: apps/v1
# This will be the deployment setup
kind: Deployment
metadata:
  # Name your Deployment here
  name: example-app-dep
  labels:
    # label your deployment
    app: example-rest-api
spec:
  # The number of pods/replicas to run
  replicas: 2
  selector:
    matchLabels:
    # selector to match the pod
      app: example-rest-api
  template:
    metadata:
      labels:
      # label your pod
        app: example-rest-api
    spec:
      containers:
      # Add the container name for Kubernetes
      - name: demo-rest-api
      # Add the local image name
        image: demo:app
        # never pull the image policy
        imagePullPolicy: Never
        ports:
        # port for running the container
        - containerPort: 9000
---
# First, add the Service API
apiVersion: v1
# This will be the Service setup
kind: Service
metadata:
  # Your service name
  name: example-rest-api-src
spec:
  selector:
    # selector that matches the pod
    app: example-rest-api
  # type of service
  type: LoadBalancer
  ports:
  - protocol: TCP
    # port for exposing the service
    port: 5000
    # portfor exposing the pod
    targetPort: 9000
    # port for exposing the node
    nodePort: 31110